# Site wide configuration

title:            lewismcgeary.github.io
locale:           en_GB
url:              https://lewismcgeary.github.io
#https://lewismcgeary.github.io for publishing
#http://localhost:4000 for local testing

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Lewis McGeary
  avatar: bio-photo.jpg
  bio: "Making things with code in Scotland. Talk to me about Android development."
  email: 
  disqus-shortname: lewismcgearygithubio
  twitter: lewismcgeary
  facebook: #username
  google:
    plus: LewisMcGeary
    analytics: UA-69454803-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lewismcgeary
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
